ТЗ-13. Добавлены эндпоинты по работае с users и items
IrinaGross/java-shareit pull request #1
Opened 2023-06-04 16:52 UTC by IrinaGross

2023-06-04 18:55 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь несколько небольших замечаний

2023-06-04 18:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * TODO Sprint add-bookings.
Можно удалить неактуальный комментарий

2023-06-04 18:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> getItems(@RequestHeader(X_SHARER_USER_ID_HEADER) @NonNull Long userId) {
Можно использовать примитивный long, чтобы не проверять на non null

2023-06-04 18:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +                .filter(it -> Objects.equals(it.getId(), itemId))
Можно хранить еще одну мапу в данном классе: itemId -> Item - так будет эффективнее

2023-06-04 18:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +        boolean exist = users.values()
Можно хранить в данном классе Set из email, чтобы быстрее проверять здесь существование

2023-06-04 18:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +            @RequestBody NoValidUserDto userDto
Рекомендация к улучшению:
Можно завести два пустых интерфейса, например, Create и Update.
Тогда в аннотациях Validated и аннотациях для валидации (NonNull, NotEmpty, ...) можно задать параметр groups, как `@NotNull(groups = {Create.class})`, тогда не нужно создавать две реализации dto и просто разбить валидацию с помощью групп

2023-06-10 06:09 UTC, IrinaGross commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +        boolean exist = users.values()
Set здесь не поможет. Необходима связка userId и email для проверки.

2023-06-12 12:32 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-07-11 13:29 UTC, merged