Add bookings
IrinaGross/java-shareit pull request #2
Opened 2023-07-13 09:23 UTC by IrinaGross

2023-07-13 20:15 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь пару замечаний

2023-07-13 20:15 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +//    private final String itemName;
Закомментированного кода быть не должно :)

2023-07-13 20:15 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/repository/JpaUserRepository.java
> +    default User getById(@NonNull Long userId) {
Лучше было бы сделать так, чтобы репозиторий только знал про сущности (UserEntity), а сама логика (преобразования, валидации) была бы уже в сервисе

2023-07-14 06:49 UTC, IrinaGross commented on src/main/java/ru/practicum/shareit/user/repository/JpaUserRepository.java
> +    default User getById(@NonNull Long userId) {
Я изначально делала так, чтобы в сервисах не нужно было ничего переделывать. Контракт репозитория остался старым, поменялась только его реализация

2023-07-14 08:25 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-07-14 09:23 UTC, merged